FROM maven:3.9.9-eclipse-temurin-21 AS deps

WORKDIR /app

COPY pom.xml ./
RUN mvn -DskipTests dependency:go-offline

FROM deps AS dev

COPY src ./src

EXPOSE 8080

CMD ["mvn", "spring-boot:run"]

FROM deps AS build

COPY src ./src

RUN mvn -DskipTests package

FROM eclipse-temurin:21-jre-alpine AS runtime

WORKDIR /app

COPY --from=build /app/target/*.jar /app/app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]